### ISSUE TITLE
There was no response  in the coppeliasim after I run playgound.ipynb

### ISSUE THREAD

**Issue by Benxiaogu** [huangwl18/VoxPoser#29]
![2024-10-22 22-40-51 的屏幕截图](https://github.com/user-attachments/assets/a979e2eb-efc4-493e-9c71-4a3e7b053789)
![2024-10-22 22-48-48 的屏幕截图](https://github.com/user-attachments/assets/0a68bee9-98f7-496e-aa27-913722d52da5)

After I run playgound.ipynb (https://github.com/huangwl18/VoxPoser/blob/main/src/playground.ipynb) there was no response  in the coppeliasim. If any of you know how to deal with it, please let me know, I would appreciate it!

**Comment by git183nuozhe** [comment]
are you solved？i have the same problem, pain

**Comment by Benxiaogu** [comment]
> are you solved？i have the same problem, pain

No, I still haven't solved it.

**Comment by tongjilyh** [comment]
看看第一张图的完整输出的结果啵，看看在哪一步卡着了。

**Comment by Benxiaogu** [comment]
> 看看第一张图的完整输出的结果啵，看看在哪一步卡着了。

你好，我完整的输出是这样的
![2024-11-18 13-04-33 的屏幕截图](https://github.com/user-attachments/assets/2c1064b7-fa82-445c-be77-4b97806602cf)
![2024-11-18 13-04-49 的屏幕截图](https://github.com/user-attachments/assets/6bfc7680-181f-4542-bfa0-9c5d4dc53a62)
![2024-11-18 13-03-18 的屏幕截图](https://github.com/user-attachments/assets/66446d23-e7e9-4353-80c7-59d88b363a18)
请问，能看出问题在哪吗

**Comment by Benxiaogu** [comment]
> 看看第一张图的完整输出的结果啵，看看在哪一步卡着了。

![2024-11-18 13-14-39 的屏幕截图](https://github.com/user-attachments/assets/c424e4fb-5f36-4637-beff-85cc70641c6e)
![2024-11-18 13-14-54 的屏幕截图](https://github.com/user-attachments/assets/bfbc275e-2d96-448a-826d-9382557ba5e8)

![2024-11-18 13-12-47 的屏幕截图](https://github.com/user-attachments/assets/188c0c81-01e7-45ae-88ef-be2b5ff332a8)
你好，根据这个完整输出应该是最终回到了默认位置了吧，请问你能看出问题吗

**Comment by tongjilyh** [comment]
诶，你这咋这么多39；49这些符号啊，我没这些像乱码的数字，是不是因为这个原因。这些语句最后是要搞到一个叫ret_val（）的实例中执行并返回相应的值，有符号的话是执行不动的应该。
而且最后回到默认位置的输出前面应该有路径执行的输出的，示意图是第二张图的蓝色文字。
![微信图片_20241118131743](https://github.com/user-attachments/assets/c492038e-1658-4406-8214-3cc320a40271)
![微信图片_20241118131947](https://github.com/user-attachments/assets/f4b0b2cb-002c-4f96-bae4-662fc54d0a81)

**Comment by Benxiaogu** [comment]
> 诶，你这咋这么多39；49这些符号啊，我没这些像乱码的数字，是不是因为这个原因。这些语句最后是要搞到一个叫ret_val（）的实例中执行并返回相应的值，有符号的话是执行不动的应该。 而且最后回到默认位置的输出前面应该有路径执行的输出的，示意图是第二张图的蓝色文字。 ![微信图片_20241118131743](https://private-user-images.githubusercontent.com/186453620/387072728-c492038e-1658-4406-8214-3cc320a40271.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MTA5OTQsIm5iZiI6MTczMTkxMDY5NCwicGF0aCI6Ii8xODY0NTM2MjAvMzg3MDcyNzI4LWM0OTIwMzhlLTE2NTgtNDQwNi04MjE0LTNjYzMyMGE0MDI3MS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOFQwNjE4MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjZkNzI5MTllNWNlMmJkMjQ4ZGIzZWIzMDgxYzRlZjc5ZWEzZGFhZDFhYTE0ZmJiYWZjYjA4YTkyYmZmMzNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.N0swGAR1oQWFvQZFMMRU-kLpM5d-hszqIRWdEf0mUp4) ![微信图片_20241118131947](https://private-user-images.githubusercontent.com/186453620/387073377-f4b0b2cb-002c-4f96-bae4-662fc54d0a81.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MTA5OTQsIm5iZiI6MTczMTkxMDY5NCwicGF0aCI6Ii8xODY0NTM2MjAvMzg3MDczMzc3LWY0YjBiMmNiLTAwMmMtNGY5Ni1iYWU0LTY2MmZjNTRkMGE4MS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOFQwNjE4MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmQ1OTRhODU0YWI5NDJkMWFmYTM5Y2Q5OWZkM2ZlZDRjYzM5Yjc3ZmZiNjliOWNhYmIxYzA2OGI0ODIwMjEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ulrFNgjN3AkPv2dhVc_eEPE2qNqFAiusmMcwMnd0ToI)

这应该是问题所在了，可以问下你使用的gpt版本吗

**Comment by Benxiaogu** [comment]
朋友，我刚刚在下图中的注释部分(之前没有注释掉)添加了注释，于是问题就解决了，谢谢你！
![2024-11-18 14-33-39 的屏幕截图](https://github.com/user-attachments/assets/afc5fb34-bda7-4bd7-8e0f-ec3aa0483290)

**Comment by tongjilyh** [comment]
> > 诶，你这咋这么多39；49这些符号啊，我没这些像乱码的数字，是不是因为这个原因。这些语句最后是要搞到一个叫ret_val（）的实例中执行并返回相应的值，有符号的话是执行不动的应该。 而且最后回到默认位置的输出前面应该有路径执行的输出的，示意图是第二张图的蓝色文字。 ![微信图片_20241118131743](https://private-user-images.githubusercontent.com/186453620/387072728-c492038e-1658-4406-8214-3cc320a40271.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MTA5OTQsIm5iZiI6MTczMTkxMDY5NCwicGF0aCI6Ii8xODY0NTM2MjAvMzg3MDcyNzI4LWM0OTIwMzhlLTE2NTgtNDQwNi04MjE0LTNjYzMyMGE0MDI3MS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOFQwNjE4MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjZkNzI5MTllNWNlMmJkMjQ4ZGIzZWIzMDgxYzRlZjc5ZWEzZGFhZDFhYTE0ZmJiYWZjYjA4YTkyYmZmMzNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.N0swGAR1oQWFvQZFMMRU-kLpM5d-hszqIRWdEf0mUp4) ![微信图片_20241118131947](https://private-user-images.githubusercontent.com/186453620/387073377-f4b0b2cb-002c-4f96-bae4-662fc54d0a81.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MTA5OTQsIm5iZiI6MTczMTkxMDY5NCwicGF0aCI6Ii8xODY0NTM2MjAvMzg3MDczMzc3LWY0YjBiMmNiLTAwMmMtNGY5Ni1iYWU0LTY2MmZjNTRkMGE4MS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOFQwNjE4MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmQ1OTRhODU0YWI5NDJkMWFmYTM5Y2Q5OWZkM2ZlZDRjYzM5Yjc3ZmZiNjliOWNhYmIxYzA2OGI0ODIwMjEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ulrFNgjN3AkPv2dhVc_eEPE2qNqFAiusmMcwMnd0ToI)
> 
> 这应该是问题所在了，可以问下你使用的gpt版本吗

我用的是gpt4omini，执行效果不错。gpt3.5就效果很烂，你注释掉的部分是修改配置文件里面使用模型类型的代码，仔细阅读一下那个注释。

**Comment by tongjilyh** [comment]
> 朋友，我刚刚在下图中的注释部分(之前没有注释掉)添加了注释，于是问题就解决了，谢谢你！ ![2024-11-18 14-33-39 的屏幕截图](https://private-user-images.githubusercontent.com/93341372/387091338-afc5fb34-bda7-4bd7-8e0f-ec3aa0483290.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MTU5NDYsIm5iZiI6MTczMTkxNTY0NiwicGF0aCI6Ii85MzM0MTM3Mi8zODcwOTEzMzgtYWZjNWZiMzQtYmRhNy00YmQ3LThlMGYtZWMzYWEwNDgzMjkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDA3NDA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjZjg5YWQ2ZGFjNGQ5OGZlNWRkZDk3YmM3N2E3MzFlOWNlNTYzODcxZTJmNDA5NDExYTUzNTY5ZDBlODU4Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.r7q0OtCTK9fSikDx1fV3E5sdnFdPBtMCXCFLqbBxM8M)

不客气啦，这个voxposer项目的代码还有很多地方需要改进，我计划一点点debug把这个代码吃透。老哥要是有兴趣研究这个的话咱们可以加个V多多交流啊。

**Comment by Benxiaogu** [comment]
> > 朋友，我刚刚在下图中的注释部分(之前没有注释掉)添加了注释，于是问题就解决了，谢谢你！ ![2024-11-18 14-33-39 的屏幕截图](https://private-user-images.githubusercontent.com/93341372/387091338-afc5fb34-bda7-4bd7-8e0f-ec3aa0483290.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MTU5NDYsIm5iZiI6MTczMTkxNTY0NiwicGF0aCI6Ii85MzM0MTM3Mi8zODcwOTEzMzgtYWZjNWZiMzQtYmRhNy00YmQ3LThlMGYtZWMzYWEwNDgzMjkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDA3NDA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjZjg5YWQ2ZGFjNGQ5OGZlNWRkZDk3YmM3N2E3MzFlOWNlNTYzODcxZTJmNDA5NDExYTUzNTY5ZDBlODU4Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.r7q0OtCTK9fSikDx1fV3E5sdnFdPBtMCXCFLqbBxM8M)
> 
> 不客气啦，这个voxposer项目的代码还有很多地方需要改进，我计划一点点debug把这个代码吃透。老哥要是有兴趣研究这个的话咱们可以加个V多多交流啊。

可以的啊 我VX号xiaoguyaojinbu
